# -*- coding: utf-8 -*-
"""Dynamic Pricing Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYFpJieqG8KEPx14SnH9mponZg8TNRxg
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

class ECommercePricingEnv:
    def __init__(self):
        self.current_price = 50
        self.max_price = 100
        self.min_price = 10
        self.max_steps = 100
        self.current_step = 0
        self.q_table = np.zeros((self.max_price - self.min_price + 1, 10))  # [price_state, actions]

    def step(self, action):
        price_change = action - 5
        self.current_price += price_change
        self.current_price = max(self.min_price, min(self.max_price, self.current_price))

        demand_factor = max(0.1, 1 - (self.current_price / 100))
        sales = demand_factor * 100
        reward = self.current_price * sales

        self.current_step += 1
        done = self.current_step >= self.max_steps
        return self.current_price, reward, done

    def reset(self):
        self.current_price = 50
        self.current_step = 0
        return self.current_price

# SARSA parameters
num_episodes = 5000
learning_rate = 0.1
discount_factor = 0.9
epsilon = 1.0
epsilon_min = 0.01
epsilon_decay = 0.001

env = ECommercePricingEnv()
total_rewards = []

for episode in range(num_episodes):
    state = env.reset()
    state_idx = state - env.min_price

    # Choose initial action (epsilon-greedy)
    if np.random.rand() < epsilon:
        action = np.random.randint(0, 10)
    else:
        action = np.argmax(env.q_table[state_idx])

    total_reward = 0
    done = False

    while not done:
        next_state, reward, done = env.step(action)
        next_state_idx = next_state - env.min_price

        # Choose next action (on-policy)
        if np.random.rand() < epsilon:
            next_action = np.random.randint(0, 10)
        else:
            next_action = np.argmax(env.q_table[next_state_idx])

        # SARSA update rule
        current_q = env.q_table[state_idx, action]
        next_q = env.q_table[next_state_idx, next_action]
        env.q_table[state_idx, action] += learning_rate * (reward + discount_factor * next_q - current_q)

        state_idx = next_state_idx
        action = next_action
        total_reward += reward

    total_rewards.append(total_reward)
    epsilon = max(epsilon_min, epsilon * (1 - epsilon_decay))

# Plotting results
plt.plot(range(num_episodes), total_rewards)
plt.xlabel('Episode')
plt.ylabel('Total Reward')
plt.title('SARSA: Total Reward per Episode')
plt.show()